name: dSatabases
version: "3.7"
services:
  mysql-db:
   container_name: mysql-db
   image: mysql:8.0

   ports:
    - "3306:3306"
   environment:
    MYSQL_ROOT_PASSWORD: "SuperSenha@10"
    MYSQL_DATABASE: "testdb"
   volumes:
    - mysql_data:/var/lib/mysql
    - C:/container_compartilhado:/shared